description = "EWS Servlet example"
tags = ["web", "servlet", "http", "json"]
name = "ews_samples"
version = "1.7.1"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["ews_samples.gpr"]
website = "https://gitlab.com/stcarrez/ada-servlet"

[[depends-on]]
servletada = "^1.7.0"
servletada_ews = "*"

[configuration]
disabled = true

[[pins]]
servletada = { path = '../..' }
servletada_ews = { path = '../../ews' }
